sudo: false
language: c
env:
    # ------------ #
    # GHC-7.6 #

    ## No remote configs
    - CABALVER=1.18 GHCVER=7.6.3 REMOTE_CONFIGS=-f-remote-configs TRANSFORMERS_B=0.4
    # - CABALVER=1.18 GHCVER=7.6.3 REMOTE_CONFIGS=-f-remote-configs TRANSFORMERS_B=10

    # - CABALVER=1.20 GHCVER=7.6.3 REMOTE_CONFIGS=-f-remote-configs TRANSFORMERS_B=0.4
    # - CABALVER=1.20 GHCVER=7.6.3 REMOTE_CONFIGS=-f-remote-configs TRANSFORMERS_B=10

    # - CABALVER=1.22 GHCVER=7.6.3 REMOTE_CONFIGS=-f-remote-configs TRANSFORMERS_B=0.4
    # - CABALVER=1.22 GHCVER=7.6.3 REMOTE_CONFIGS=-f-remote-configs TRANSFORMERS_B=10

    ## Remote configs
    - CABALVER=1.18 GHCVER=7.6.3 REMOTE_CONFIGS=-f+remote-configs TRANSFORMERS_B=0.4
    # - CABALVER=1.18 GHCVER=7.6.3 REMOTE_CONFIGS=-f+remote-configs TRANSFORMERS_B=10

    - CABALVER=1.20 GHCVER=7.6.3 REMOTE_CONFIGS=-f+remote-configs TRANSFORMERS_B=0.4
    # - CABALVER=1.20 GHCVER=7.6.3 REMOTE_CONFIGS=-f+remote-configs TRANSFORMERS_B=10

    # - CABALVER=1.22 GHCVER=7.6.3 REMOTE_CONFIGS=-f+remote-configs TRANSFORMERS_B=0.4
    - CABALVER=1.22 GHCVER=7.6.3 REMOTE_CONFIGS=-f+remote-configs TRANSFORMERS_B=10

    # ------------ #
    # GHC-7.8 #

    ## No remote configs
    - CABALVER=1.18 GHCVER=7.8.4 REMOTE_CONFIGS=-f-remote-configs TRANSFORMERS_B=0.4
    # - CABALVER=1.18 GHCVER=7.8.4 REMOTE_CONFIGS=-f-remote-configs TRANSFORMERS_B=10

    # - CABALVER=1.20 GHCVER=7.8.4 REMOTE_CONFIGS=-f-remote-configs TRANSFORMERS_B=0.4
    # - CABALVER=1.20 GHCVER=7.8.4 REMOTE_CONFIGS=-f-remote-configs TRANSFORMERS_B=10

    - CABALVER=1.22 GHCVER=7.8.4 REMOTE_CONFIGS=-f-remote-configs TRANSFORMERS_B=0.4
    # - CABALVER=1.22 GHCVER=7.8.4 REMOTE_CONFIGS=-f-remote-configs TRANSFORMERS_B=10

    ## Remote configs
    - CABALVER=1.18 GHCVER=7.8.4 REMOTE_CONFIGS=-f+remote-configs TRANSFORMERS_B=0.4
    - CABALVER=1.18 GHCVER=7.8.4 REMOTE_CONFIGS=-f+remote-configs TRANSFORMERS_B=10

    - CABALVER=1.20 GHCVER=7.8.4 REMOTE_CONFIGS=-f+remote-configs TRANSFORMERS_B=0.4
    - CABALVER=1.20 GHCVER=7.8.4 REMOTE_CONFIGS=-f+remote-configs TRANSFORMERS_B=10

    - CABALVER=1.22 GHCVER=7.8.4 REMOTE_CONFIGS=-f+remote-configs TRANSFORMERS_B=0.4
    - CABALVER=1.22 GHCVER=7.8.4 REMOTE_CONFIGS=-f+remote-configs TRANSFORMERS_B=10

    # ------------ #
    # GHC-7.10 #

    ## No remote configs
    - CABALVER=1.22 GHCVER=7.10.1 REMOTE_CONFIGS=-f-remote-configs TRANSFORMERS_B=10

    ## Remote configs
    - CABALVER=1.22 GHCVER=7.10.1 REMOTE_CONFIGS=-f+remote-configs TRANSFORMERS_B=10

addons:
    apt:
        sources:
            - hvr-ghc
        packages:
            - cabal-install-1.18
            - cabal-install-1.20
            - cabal-install-1.22
            - ghc-7.6.3
            - ghc-7.8.4
            - ghc-7.10.1

before_install:
    - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
    - export EXACT_CABALVER=$(cabal --version | sed -n '2s/.*version \(.*\) of.*/\1/p')
    - echo EXACT_CABALVER=$EXACT_CABALVER

install:
    - cabal --version
    - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
    - travis_retry cabal update
    - cabal install --only-dependencies --enable-tests --enable-benchmarks --constraint="Cabal==$EXACT_CABALVER" --constraint="transformers<$TRANSFORMERS_B"

script:
    - cabal configure --enable-tests --enable-benchmarks -v --constraint="Cabal==$EXACT_CABALVER" --constraint="transformers<$TRANSFORMERS_B"
    - cabal build
    - cabal test
    - cabal check
    - cabal sdist

    # check that the generated source-distribution can be built & installed
    - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
      (cd dist && cabal install --force-reinstalls "$SRC_TGZ" --constraint="Cabal==$EXACT_CABALVER" --constraint="transformers<$TRANSFORMERS_B")

