language: haskell
ghc:
    - 7.6
    - 7.8
env:
    - OPTPARSE_APPLICATIVE_BOUND=0.11 REMOTE_CONFIGS=-f-remote-configs CABALBOUND=1.20 CABALVER=1.18
    - OPTPARSE_APPLICATIVE_BOUND=10 REMOTE_CONFIGS=-fremote-configs CABALBOUND=1.20 CABALVER=1.18

    - OPTPARSE_APPLICATIVE_BOUND=0.11 REMOTE_CONFIGS=-f-remote-configs CABALBOUND=1.22 CABALVER=1.20
    - OPTPARSE_APPLICATIVE_BOUND=10 REMOTE_CONFIGS=-fremote-configs CABALBOUND=1.22 CABALVER=1.20

    - OPTPARSE_APPLICATIVE_BOUND=0.11 REMOTE_CONFIGS=-f-remote-configs CABALBOUND=2 CABALVER=1.22
    - OPTPARSE_APPLICATIVE_BOUND=10 REMOTE_CONFIGS=-fremote-configs CABALBOUND=2 CABALVER=1.22

matrix:
    exclude:
        - env: OPTPARSE_APPLICATIVE_BOUND=0.11 REMOTE_CONFIGS=-f-remote-configs CABALBOUND=2 CABALVER=1.22
          ghc: 7.6
        - env: OPTPARSE_APPLICATIVE_BOUND=10 REMOTE_CONFIGS=-fremote-configs CABALBOUND=2 CABALVER=1.22
          ghc: 7.6

before_install:
    # - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
    # - travis_retry sudo apt-get update
    # - travis_retry sudo apt-get install cabal-install-$CABALVER
    # - export PATH=/opt/cabal/$CABALVER/bin:$PATH
    - travis_retry cabal update
    - mkdir $HOME/bin
    - travis_retry cabal install cabal-install --bindir=$HOME/bin --constraint="Cabal<$CABALBOUND"
    - export PATH=$HOME/bin:$PATH

install:
    - cabal --version
    - travis_retry cabal update
    - cabal install --only-dependencies --enable-tests --constraint="optparse-applicative<$OPTPARSE_APPLICATIVE_BOUND" --constraint="Cabal<$CABALBOUND" $REMOTE_CONFIGS

script:
    - cabal clean
    - cabal configure --enable-tests --constraint="optparse-applicative<$OPTPARSE_APPLICATIVE_BOUND" --constraint="Cabal<$CABALBOUND" $REMOTE_CONFIGS
    - cabal build
    - cabal test
    - cabal sdist

