sudo: false
language: c

matrix:
    include:
        # ------------ #
        # GHC-7.10 #

        - env: CABALVER=1.22 GHCVER=7.10.3 REMOTE_CONFIGS=-f-remote-configs
          addons: {apt: {packages: [cabal-install-1.22, ghc-7.10.3], sources: [hvr-ghc]}}
        # - env: CABALVER=1.22 GHCVER=7.10.3 REMOTE_CONFIGS=-f+remote-configs
        #   addons: {apt: {packages: [cabal-install-1.22, ghc-7.10.3], sources: [hvr-ghc]}}

        # ------------ #
        # GHC-8.0.2 #

        - env: CABALVER=1.24 GHCVER=8.0.2 REMOTE_CONFIGS=-f-remote-configs
          addons: {apt: {packages: [cabal-install-1.24, ghc-8.0.2], sources: [hvr-ghc]}}
        - env: CABALVER=1.24 GHCVER=8.0.2 REMOTE_CONFIGS=-f+remote-configs
          addons: {apt: {packages: [cabal-install-1.24, ghc-8.0.2], sources: [hvr-ghc]}}

        # ------------ #
        # GHC-8.2.2, cabal-install 1.24 #

        - env: CABALVER=1.24 GHCVER=8.2.2 REMOTE_CONFIGS=-f-remote-configs
          addons: {apt: {packages: [cabal-install-1.24, ghc-8.2.2], sources: [hvr-ghc]}}
        - env: CABALVER=1.24 GHCVER=8.2.2 REMOTE_CONFIGS=-f+remote-configs
          addons: {apt: {packages: [cabal-install-1.24, ghc-8.2.2], sources: [hvr-ghc]}}

        # ------------ #
        # GHC-8.2.2, cabal-install-2.0 #

        - env: CABALVER=2.0 GHCVER=8.2.2 REMOTE_CONFIGS=-f-remote-configs
          addons: {apt: {packages: [cabal-install-2.0, ghc-8.2.2], sources: [hvr-ghc]}}
        - env: CABALVER=2.0 GHCVER=8.2.2 REMOTE_CONFIGS=-f+remote-configs
          addons: {apt: {packages: [cabal-install-2.0, ghc-8.2.2], sources: [hvr-ghc]}}

        # ------------ #
        # GHC-8.4.3, cabal-install-2.2 #

        - env: CABALVER=2.2 GHCVER=8.4.3 REMOTE_CONFIGS=-f-remote-configs
          addons: {apt: {packages: [cabal-install-2.2, ghc-8.4.3], sources: [hvr-ghc]}}
        - env: CABALVER=2.2 GHCVER=8.4.3 REMOTE_CONFIGS=-f+remote-configs
          addons: {apt: {packages: [cabal-install-2.2, ghc-8.4.3], sources: [hvr-ghc]}}

before_install:
    - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
    - cabal --version
    - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
    - travis_retry cabal update
    - cabal install --only-dependencies --enable-tests --enable-benchmarks $REMOTE_CONFIGS --max-backjumps=10000

script:
    - cabal configure --enable-tests --enable-benchmarks -v $REMOTE_CONFIGS
    - cabal build
    - cabal test
    - cabal check
    - cabal sdist

    # check that the generated source-distribution can be built & installed
    - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
      (cd dist && cabal install --force-reinstalls "$SRC_TGZ")

