sudo: false
language: haskell
ghc:
    - '7.6'
    - '7.8'
    - '7.10'
env:
    - REMOTE_CONFIGS=-f-remote-configs CABAL_B=1.20 TRANSFORMERS_B=0.4
    - REMOTE_CONFIGS=-f-remote-configs CABAL_B=1.20 TRANSFORMERS_B=10

    - REMOTE_CONFIGS=-f-remote-configs CABAL_B=1.22 TRANSFORMERS_B=0.4
    - REMOTE_CONFIGS=-f-remote-configs CABAL_B=1.22 TRANSFORMERS_B=10

    - REMOTE_CONFIGS=-f-remote-configs CABAL_B=1000 TRANSFORMERS_B=0.4
    - REMOTE_CONFIGS=-f-remote-configs CABAL_B=1000 TRANSFORMERS_B=10

    - REMOTE_CONFIGS=-f+remote-configs CABAL_B=1.20 TRANSFORMERS_B=0.4
    - REMOTE_CONFIGS=-f+remote-configs CABAL_B=1.20 TRANSFORMERS_B=10

    - REMOTE_CONFIGS=-f+remote-configs CABAL_B=1.22 TRANSFORMERS_B=0.4
    - REMOTE_CONFIGS=-f+remote-configs CABAL_B=1.22 TRANSFORMERS_B=10

    - REMOTE_CONFIGS=-f+remote-configs CABAL_B=1000 TRANSFORMERS_B=0.4
    - REMOTE_CONFIGS=-f+remote-configs CABAL_B=1000 TRANSFORMERS_B=10

matrix:
    exclude:
        # exlude everything
        - ghc: '7.6'
        - ghc: '7.8'
        - ghc: '7.10'
    include:
        #include selected entries

        # GHC-7.6 #

        ## No remote configs
        - env: REMOTE_CONFIGS=-f-remote-configs CABAL_B=1.20 TRANSFORMERS_B=0.4
          ghc: '7.6'
        # - env: REMOTE_CONFIGS=-f-remote-configs CABAL_B=1.20 TRANSFORMERS_B=10
        #   ghc: '7.6'

        # - env: REMOTE_CONFIGS=-f-remote-configs CABAL_B=1.22 TRANSFORMERS_B=0.4
        #   ghc: '7.6'
        # - env: REMOTE_CONFIGS=-f-remote-configs CABAL_B=1.22 TRANSFORMERS_B=10
        #  ghc: '7.6'

        # - env: REMOTE_CONFIGS=-f-remote-configs CABAL_B=1000 TRANSFORMERS_B=0.4
        #   ghc: '7.6'
        # - env: REMOTE_CONFIGS=-f-remote-configs CABAL_B=1000 TRANSFORMERS_B=10
        #   ghc: '7.6'

        ## Remote configs
        - env: REMOTE_CONFIGS=-f+remote-configs CABAL_B=1.20 TRANSFORMERS_B=0.4
          ghc: '7.6'
        # - env: REMOTE_CONFIGS=-f+remote-configs CABAL_B=1.20 TRANSFORMERS_B=10
        #   ghc: '7.6'

        - env: REMOTE_CONFIGS=-f+remote-configs CABAL_B=1.22 TRANSFORMERS_B=0.4
          ghc: '7.6'
        # - env: REMOTE_CONFIGS=-f+remote-configs CABAL_B=1.22 TRANSFORMERS_B=10
        #   ghc: '7.6'

        - env: REMOTE_CONFIGS=-f+remote-configs CABAL_B=1000 TRANSFORMERS_B=0.4
          ghc: '7.6'
        - env: REMOTE_CONFIGS=-f+remote-configs CABAL_B=1000 TRANSFORMERS_B=10
          ghc: '7.6'

        # GHC-7.8 #

        ## No remote configs
        - env: REMOTE_CONFIGS=-f-remote-configs CABAL_B=1.20 TRANSFORMERS_B=0.4
          ghc: '7.8'
        # - env: REMOTE_CONFIGS=-f-remote-configs CABAL_B=1.20 TRANSFORMERS_B=10
        #   ghc: '7.8'

        # - env: REMOTE_CONFIGS=-f-remote-configs CABAL_B=1.22 TRANSFORMERS_B=0.4
        #   ghc: '7.8'
        # - env: REMOTE_CONFIGS=-f-remote-configs CABAL_B=1.22 TRANSFORMERS_B=10
        #   ghc: '7.8'

        # - env: REMOTE_CONFIGS=-f-remote-configs CABAL_B=1000 TRANSFORMERS_B=0.4
        #   ghc: '7.8'
        # - env: REMOTE_CONFIGS=-f-remote-configs CABAL_B=1000 TRANSFORMERS_B=10
        #   ghc: '7.8'

        ## Remote configs
        - env: REMOTE_CONFIGS=-f+remote-configs CABAL_B=1.20 TRANSFORMERS_B=0.4
          ghc: '7.8'
        - env: REMOTE_CONFIGS=-f+remote-configs CABAL_B=1.20 TRANSFORMERS_B=10
          ghc: '7.8'

        - env: REMOTE_CONFIGS=-f+remote-configs CABAL_B=1.22 TRANSFORMERS_B=0.4
          ghc: '7.8'
        - env: REMOTE_CONFIGS=-f+remote-configs CABAL_B=1.22 TRANSFORMERS_B=10
          ghc: '7.8'

        - env: REMOTE_CONFIGS=-f+remote-configs CABAL_B=1000 TRANSFORMERS_B=0.4
          ghc: '7.8'
        - env: REMOTE_CONFIGS=-f+remote-configs CABAL_B=1000 TRANSFORMERS_B=10
          ghc: '7.8'

        # GHC-7.10 #

        ## No remote configs
        # - env: REMOTE_CONFIGS=-f-remote-configs CABAL_B=1.20 TRANSFORMERS_B=0.4
        #   ghc: '7.10'
        # - env: REMOTE_CONFIGS=-f-remote-configs CABAL_B=1.20 TRANSFORMERS_B=10
        #   ghc: '7.10'

        # - env: REMOTE_CONFIGS=-f-remote-configs CABAL_B=1.22 TRANSFORMERS_B=0.4
        #   ghc: '7.10'
        # - env: REMOTE_CONFIGS=-f-remote-configs CABAL_B=1.22 TRANSFORMERS_B=10
        #   ghc: '7.10'

        # - env: REMOTE_CONFIGS=-f-remote-configs CABAL_B=1000 TRANSFORMERS_B=0.4
        #   ghc: '7.10'
        - env: REMOTE_CONFIGS=-f-remote-configs CABAL_B=1000 TRANSFORMERS_B=10
          ghc: '7.10'

        ## Remote configs
        # - env: REMOTE_CONFIGS=-f+remote-configs CABAL_B=1.20 TRANSFORMERS_B=0.4
        #   ghc: '7.10'
        # - env: REMOTE_CONFIGS=-f+remote-configs CABAL_B=1.20 TRANSFORMERS_B=10
        #   ghc: '7.10'

        # - env: REMOTE_CONFIGS=-f+remote-configs CABAL_B=1.22 TRANSFORMERS_B=0.4
        #   ghc: '7.10'
        # - env: REMOTE_CONFIGS=-f+remote-configs CABAL_B=1.22 TRANSFORMERS_B=10
        #   ghc: '7.10'

        # - env: REMOTE_CONFIGS=-f+remote-configs CABAL_B=1000 TRANSFORMERS_B=0.4
        #   ghc: '7.10'
        - env: REMOTE_CONFIGS=-f+remote-configs CABAL_B=1000 TRANSFORMERS_B=10
          ghc: '7.10'

before_install:
    # - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
    # - travis_retry sudo apt-get update
    # - travis_retry sudo apt-get install cabal-install-$CABALVER
    # - export PATH=/opt/cabal/$CABALVER/bin:$PATH
    - travis_retry cabal update
    - mkdir $HOME/bin
    - travis_retry cabal install cabal-install --bindir=$HOME/bin --constraint="Cabal<$CABAL_B" --constraint="transformers<$TRANSFORMERS_B"
    - export PATH=$HOME/bin:$PATH

install:
    - cabal --version
    - travis_retry cabal update
    - cabal install --only-dependencies --enable-tests --constraint="Cabal<$CABAL_B" --constraint="transformers<$TRANSFORMERS_B" $REMOTE_CONFIGS

script:
    - cabal clean
    - cabal configure --enable-tests --constraint="Cabal<$CABAL_B" --constraint="transformers<$TRANSFORMERS_B" $REMOTE_CONFIGS
    - cabal build
    - cabal test
    - cabal sdist

