name: Build with Cabal

on: ['push']

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.8.4', '8.10.7', '9.0.1']
        cabal: ['3.4.0.0']
        os: ['ubuntu-18.04', 'ubuntu-20.04', 'macOS-latest']
        remoteConfigs: ['-remote-configs', '+remote-configs']
        include:
        - ghc: '9.2'
          cabal: '3.6.2.0'
          os: 'ubuntu-20.04'
          remoteConfigs: '+remote-configs'

    steps:

    # Setup
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install GHC and Cabal
      uses: larskuhtz/actions/setup@e0f107055073590682bc5264b8da5c2b6af39a65
      with:
         ghc-version: ${{ matrix.ghc }}
         cabal-version: ${{ matrix.cabal }}
    - name: Configure project
      run: |
        cat > cabal.project.local <<EOF
        package configuration-tools
          documentation: True
          benchmarks: True
          tests: True
          flags: ${{ matrix.remoteConfigs }}
        EOF

    # GHC 9.2
    - name: Configure project
      if: "startsWith(matrix.ghc, '9.2')"
      run: |
        cat >> cabal.project.local <<EOF
        constraints: aeson >=2.0
        constraints: yaml >=0.11.7.0
        allow-newer: *
        source-repository-package
          type: git
          location: https://github.com/haskell/aeson
          tag: bfc8de2a155fb6725701ec692e8a6db3986cfb36
        source-repository-package
          type: git
          location: https://github.com/snoyberg/yaml.git
          tag: c4392f3855002ab0bbf9bc16e1e32034254234a7
          subdir: yaml
        repository head.hackage.ghc.haskell.org
           url: https://ghc.gitlab.haskell.org/head.hackage/
           secure: True
           key-threshold: 3
           root-keys:
               f76d08be13e9a61a377a85e2fb63f4c5435d40f8feb3e12eb05905edb8cdea89
               26021a13b401500c8eb2761ca95c61f2d625bfef951b939a8124ed12ecf07329
               7541f32a4ccca4f97aea3b22f5e593ba2c0267546016b992dfadcd2fe944e55d

        active-repositories: hackage.haskell.org, head.hackage.ghc.haskell.org:override
        EOF

    # Restore Packages from Caches
    - uses: actions/cache@v2
      name: Cache cabal packages
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ matrix.os }}-${{ matrix.ghc }}-2-cabal

    # Build
    - name: Update package database
      run: cabal update
    - name: Configure build
      run: |
        cabal build all --dry-run
        cabal freeze
    - name: Install build dependencies
      run: cabal build --only-dependencies
    - name: Build library
      run: cabal build

    # Tests
    - name: Run Tests
      run: cabal test

